name: Generate Directory Listing and Deploy

on:
  push:
    branches:
      - main  # 본인의 기본 브랜치 이름

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 특정 폴더(예: files) 안의 파일 리스트로 index.html 자동 생성
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: "col" # 리스트를 뽑을 대상 폴더명 입력

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'col' # 배포할 폴더 경로

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
